-- CRIA DATABASE
CREATE DATABASE VXTEL;
GO

-- USA DATABASE CRIADA
USE VXTEL;
GO

-- CRIA TABELA BANCO DE DADOS
CREATE TABLE TABELACAOPRECO
(
	ID			INT	IDENTITY PRIMARY KEY,
	ORIGEM		VARCHAR(3) NOT NULL,
	DESTINO		VARCHAR(3) NOT NULL,
	CUSTOMIN	MONEY	   NOT NULL
)

GO

-- CRIA TABELA DE PLANOS FALE MAIS
CREATE TABLE PLANOSVXTEL
(
	ID				INT	IDENTITY PRIMARY KEY,
	NOMEPLANO		VARCHAR(50) NOT NULL,
	MINUTOSPLANO	INT         NOT NULL
)
GO

-- CRIA TABELA DE USUÁRIOS
CREATE TABLE VXTELUSER
(
	USUARIO		VARCHAR(30),
	SENHA		VARCHAR(30),
	PERFIL		VARCHAR(100)
)
GO

-- INSERE USUARIO
INSERT INTO VXTELUSER (USUARIO, SENHA, PERFIL)
	VALUES
		('admin', 'admin', 'administrador')
GO

-- INSERE DADOS NA TABELA
INSERT INTO TABELACAOPRECO (ORIGEM, DESTINO, CUSTOMIN)
	VALUES 
		('011', '016', 1.90),
		('016', '011', 2.90),
		('011', '017', 1.70),
		('017', '011', 2.70),
		('011', '018', 0.90),
		('018', '011', 1.90)
GO

-- INSERE OS PLANOS NA TABELA
INSERT INTO PLANOSVXTEL (NOMEPLANO, MINUTOSPLANO)
	VALUES
		('FaleMais 30', 30),
		('FaleMais 60', 60),
		('FaleMais 120', 120)
GO

-- CRIA PROCEDURE DE CONSULTA NO BANCO DE DADOS
CREATE OR ALTER PROCEDURE SP_CONSULTA_TABELACAO_PRECOS
AS

	SELECT ID, ORIGEM, DESTINO, CUSTOMIN FROM TABELACAOPRECO;
GO
-- CRIA PROCEDURE DE CONSULTA PLANOS VX TEL
CREATE OR ALTER PROCEDURE SP_CONSULTA_PLANOS
AS

	SELECT ID, NOMEPLANO, MINUTOSPLANO FROM PLANOSVXTEL;
GO

-- CRIA PROCEDURE DE CONSULTA PLANO VX TEL POR ID
CREATE OR ALTER PROCEDURE SP_CONSULTA_PLANOS_POR_ID
	@ID INT
AS

	SELECT ID, NOMEPLANO, MINUTOSPLANO FROM PLANOSVXTEL WHERE ID = @ID;
GO

-- CRIA PROCEDURE DE CONSULTA NO BANCO DE DADOS PARA REALIZAÇÃO POSTERIOR DE CALCULO
CREATE OR ALTER PROCEDURE SP_CONSULTA_TABELACAO_PRECOS_CALCULO_PLANO
	@ORIGEM		VARCHAR(3),
	@DESTINO	VARCHAR(3)
AS

	SELECT ID, ORIGEM, DESTINO, CUSTOMIN FROM TABELACAOPRECO WHERE ORIGEM = @ORIGEM AND DESTINO = @DESTINO;
GO

-- CRIA PROCEDURE DE LOGIN 
CREATE OR ALTER PROCEDURE SP_LOGIN
	@LOGIN		VARCHAR(30),
	@SENHA		VARCHAR(30)
AS

	SELECT USUARIO, SENHA, PERFIL FROM VXTELUSER WHERE USUARIO = @LOGIN AND SENHA = @SENHA;
GO

-- CRIA PROC PARA CADASTRO DE NOVO PLANO
CREATE OR ALTER PROCEDURE SP_NOVO_PLANO
	@NOMEPLANO	VARCHAR(50),
	@MINUTOS	INT,
	@OUTPUT		INT OUTPUT
AS
	INSERT INTO PLANOSVXTEL (NOMEPLANO, MINUTOSPLANO)
		VALUES
			(@NOMEPLANO, @MINUTOS)

	SET @OUTPUT = SCOPE_IDENTITY() 
GO

--CRIA SCRIPT PARA REMOVER PLANO
CREATE OR ALTER PROCEDURE SP_DELETE_PLANO
	@ID INT
AS
	DELETE FROM PLANOSVXTEL WHERE ID = @ID
GO
-- 